# Generated by Django 4.1.5 on 2023-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parsanalyzing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('book_price', models.CharField(blank=True, default='', max_length=100)),
                ('curr_price', models.CharField(blank=True, default='', max_length=100)),
                ('forw_price', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
