# Generated by Django 4.1.5 on 2023-08-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsanalyzing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsanalyzing',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
