# Generated by Django 4.1.5 on 2023-08-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsanalyzing', '0003_rename_forw_price_parsanalyzing_sfrw_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestForBuying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('short_title', models.CharField(blank=True, default='', max_length=100, unique=True)),
            ],
        ),
    ]
