# Generated by Django 4.1.5 on 2023-08-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsanalyzing', '0004_bestforbuying'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parsanalyzing',
            new_name='Parsanalyze',
        ),
    ]
