# Generated by Django 4.1.5 on 2023-08-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsanalyzing', '0005_rename_parsanalyzing_parsanalyze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestforbuying',
            name='full_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
